# Backend configuration for Production Environment - ACR
# This file is used with: terraform init -backend-config=prod/prod.conf

resource_group_name  = "rg-terraform-state"
storage_account_name = "stmcdaterraformstate"
container_name       = "tfstate"
key                  = "acr/prod/terraform.tfstate"

