# Backend configuration for Staging Environment - Database
# This file is used with: terraform init -backend-config=stage/stage.conf

resource_group_name  = "rg-terraform-state"
storage_account_name = "stmcdaterraformstate"
container_name       = "tfstate"
key                  = "db/stage/terraform.tfstate"

