# Backend configuration for Production Environment
# This file is used with: terraform init -backend-config=prod.conf

resource_group_name  = "rg-terraform-state"
storage_account_name = "stmcdaterraformstate"
container_name       = "tfstate"
key                  = "prod/terraform.tfstate"

