trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - 'frontend/**'
      - 'backend/**'
      - '.azure-pipelines/azure-pipelines-build.yml'

variables:
- group: 'infrastructure-common'

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build and push frontend (dev)
            inputs:
              command: buildAndPush
              repository: $(imageRepositoryFrontend)
              dockerfile: frontend/Dockerfile
              containerRegistry: $(dockerDeploymentDevSvc)
              buildContext: frontend
              tags: |
                latest
                dev-$(Build.BuildId)
          - task: Docker@2
            displayName: Build and push backend (dev)
            inputs:
              command: buildAndPush
              repository: $(imageRepositoryBackend)
              dockerfile: backend/Dockerfile
              containerRegistry: $(dockerDeploymentDevSvc)
              tags: |
                dev-$(Build.BuildId)
                latest
          # - task: Docker@2
          #   displayName: Build and push frontend (stage)
          #   inputs:
          #     command: buildAndPush
          #     repository: $(imageRepositoryFrontend)
          #     dockerfile: frontend/Dockerfile
          #     containerRegistry: $(dockerDeploymentStageSvc)
          #     buildContext: frontend
          #     tags: |
          #       latest
          #       stage-$(Build.BuildId)
          # - task: Docker@2
          #   displayName: Build and push backend (stage)
          #   inputs:
          #     command: buildAndPush
          #     repository: $(imageRepositoryBackend)
          #     dockerfile: backend/Dockerfile
          #     containerRegistry: $(dockerDeploymentStageSvc)
          #     tags: |
          #       latest
          #       stage-$(Build.BuildId)
          # - task: Docker@2
          #   displayName: Build and push frontend (prod)
          #   inputs:
          #     command: buildAndPush
          #     repository: $(imageRepositoryFrontend)
          #     dockerfile: frontend/Dockerfile
          #     containerRegistry: $(dockerDeploymentProdSvc)
          #     buildContext: frontend
          #     tags: |
          #       latest
          #       prod-$(Build.BuildId)
          # - task: Docker@2
          #   displayName: Build and push backend (prod)
          #   inputs:
          #     command: buildAndPush
          #     repository: $(imageRepositoryBackend)
          #     dockerfile: backend/Dockerfile
          #     containerRegistry: $(dockerDeploymentProdSvc)
          #     tags: |
          #       latest
          #       prod-$(Build.BuildId)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)'
              ArtifactName: drop
