trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - 'frontend/**'
      - 'backend/**'
      - '.azure-pipelines/azure-pipelines-build.yml'

variables:
- group: 'infrastructure-common'
- name: imageRepositoryFrontend
  value: ccps-portal/frontend
- name: imageRepositoryBackend
  value: ccps-portal/backend

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build frontend (dev)
            inputs:
              command: build
              repository: $(imageRepositoryFrontend)
              dockerfile: frontend/Dockerfile
              containerRegistry: $(dockerDeploymentDevSvc)
              buildContext: frontend
              arguments: --build-arg VITE_BACKEND_URL=$(devViteBackendUrl)
              tags: |
                latest
                dev-$(Build.BuildId)
                dev-$(Build.SourceBranchName)
          - task: Docker@2
            displayName: Push frontend (dev)
            inputs:
              command: push
              repository: $(imageRepositoryFrontend)
              containerRegistry: $(dockerDeploymentDevSvc)
              tags: |
                latest
                dev-$(Build.BuildId)
                dev-$(Build.SourceBranchName)
          - task: Docker@2
            displayName: Build backend (dev)
            inputs:
              command: build
              repository: $(imageRepositoryBackend)
              dockerfile: backend/Dockerfile
              containerRegistry: $(dockerDeploymentDevSvc)
              tags: |
                dev-$(Build.BuildId)
                dev-$(Build.SourceBranchName)
                latest
          - task: Docker@2
            displayName: Push backend (dev)
            inputs:
              command: push
              repository: $(imageRepositoryBackend)
              containerRegistry: $(dockerDeploymentDevSvc)
              tags: |
                dev-$(Build.BuildId)
                dev-$(Build.SourceBranchName)
                latest
          # - task: Docker@2
          #   displayName: Build frontend (stage)
          #   inputs:
          #     command: build
          #     repository: $(imageRepositoryFrontend)
          #     dockerfile: frontend/Dockerfile
          #     containerRegistry: $(dockerDeploymentStageSvc)
          #     buildContext: frontend
          #     arguments: --build-arg VITE_BACKEND_URL=$(stageViteBackendUrl)
          #     tags: |
          #       latest
          #       stage-$(Build.BuildId)
          #       stage-$(Build.SourceBranchName)
          # - task: Docker@2
          #   displayName: Push frontend (stage)
          #   inputs:
          #     command: push
          #     repository: $(imageRepositoryFrontend)
          #     containerRegistry: $(dockerDeploymentStageSvc)
          #     tags: |
          #       latest
          #       stage-$(Build.BuildId)
          #       stage-$(Build.SourceBranchName)
          # - task: Docker@2
          #   displayName: Build backend (stage)
          #   inputs:
          #     command: build
          #     repository: $(imageRepositoryBackend)
          #     dockerfile: backend/Dockerfile
          #     containerRegistry: $(dockerDeploymentStageSvc)
          #     tags: |
          #       latest
          #       stage-$(Build.BuildId)
          #       stage-$(Build.SourceBranchName)
          # - task: Docker@2
          #   displayName: Push backend (stage)
          #   inputs:
          #     command: push
          #     repository: $(imageRepositoryBackend)
          #     containerRegistry: $(dockerDeploymentStageSvc)
          #     tags: |
          #       latest
          #       stage-$(Build.BuildId)
          #       stage-$(Build.SourceBranchName)
          # - task: Docker@2
          #   displayName: Build frontend (prod)
          #   inputs:
          #     command: build
          #     repository: $(imageRepositoryFrontend)
          #     dockerfile: frontend/Dockerfile
          #     containerRegistry: $(dockerDeploymentProdSvc)
          #     buildContext: frontend
          #     arguments: --build-arg VITE_BACKEND_URL=$(prodViteBackendUrl)
          #     tags: |
          #       latest
          #       prod-$(Build.BuildId)
          #       prod-$(Build.SourceBranchName)
          # - task: Docker@2
          #   displayName: Push frontend (prod)
          #   inputs:
          #     command: push
          #     repository: $(imageRepositoryFrontend)
          #     containerRegistry: $(dockerDeploymentProdSvc)
          #     tags: |
          #       latest
          #       prod-$(Build.BuildId)
          #       prod-$(Build.SourceBranchName)
          # - task: Docker@2
          #   displayName: Build backend (prod)
          #   inputs:
          #     command: build
          #     repository: $(imageRepositoryBackend)
          #     dockerfile: backend/Dockerfile
          #     containerRegistry: $(dockerDeploymentProdSvc)
          #     tags: |
          #       latest
          #       prod-$(Build.BuildId)
          #       prod-$(Build.SourceBranchName)
          # - task: Docker@2
          #   displayName: Push backend (prod)
          #   inputs:
          #     command: push
          #     repository: $(imageRepositoryBackend)
          #     containerRegistry: $(dockerDeploymentProdSvc)
          #     tags: |
          #       latest
          #       prod-$(Build.BuildId)
          #       prod-$(Build.SourceBranchName)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)'
              ArtifactName: drop
