trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - 'frontend/**'
      - 'backend/**'
      - '.azure-pipelines/azure-pipelines-build.yml'

variables:
- group: 'infrastructure-common'
- group: 'infrastructure-dev'

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: AzureCLI@2
            displayName: 'Build and Push Frontend (dev)'
            inputs:
              azureSubscription: tfARM
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Login
                az acr login --name $(acrName)
                
                echo "Building and pushing frontend image..."
                az acr build --registry $(acrName) \
                              --image $(imageRepositoryFrontend):latest \
                              --image $(imageRepositoryFrontend):dev-$(Build.BuildId) \
                              --file frontend/Dockerfile \
                              frontend
              workingDirectory: '$(System.DefaultWorkingDirectory)'

          - task: AzureCLI@2
            displayName: 'Build and Push Backend (dev)'
            inputs:
              azureSubscription: tfARM
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Login
                az acr login --name $(acrName)
                
                echo "Building and pushing backend image..."
                az acr build --registry $(acrName) \
                              --image $(imageRepositoryBackend):latest \
                              --image $(imageRepositoryBackend):dev-$(Build.BuildId) \
                              --file backend/Dockerfile \
                              backend
              workingDirectory: '$(System.DefaultWorkingDirectory)'
          # - task: Docker@2
          #   displayName: Build and push frontend (stage)
          #   inputs:
          #     command: buildAndPush
          #     repository: $(imageRepositoryFrontend)
          #     dockerfile: frontend/Dockerfile
          #     containerRegistry: $(dockerDeploymentStageSvc)
          #     buildContext: frontend
          #     tags: |
          #       latest
          #       stage-$(Build.BuildId)
          # - task: Docker@2
          #   displayName: Build and push backend (stage)
          #   inputs:
          #     command: buildAndPush
          #     repository: $(imageRepositoryBackend)
          #     dockerfile: backend/Dockerfile
          #     containerRegistry: $(dockerDeploymentStageSvc)
          #     tags: |
          #       latest
          #       stage-$(Build.BuildId)
          # - task: Docker@2
          #   displayName: Build and push frontend (prod)
          #   inputs:
          #     command: buildAndPush
          #     repository: $(imageRepositoryFrontend)
          #     dockerfile: frontend/Dockerfile
          #     containerRegistry: $(dockerDeploymentProdSvc)
          #     buildContext: frontend
          #     tags: |
          #       latest
          #       prod-$(Build.BuildId)
          # - task: Docker@2
          #   displayName: Build and push backend (prod)
          #   inputs:
          #     command: buildAndPush
          #     repository: $(imageRepositoryBackend)
          #     dockerfile: backend/Dockerfile
          #     containerRegistry: $(dockerDeploymentProdSvc)
          #     tags: |
          #       latest
          #       prod-$(Build.BuildId)
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Docker Artifacts - Frontend'
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/frontend'
              ArtifactName: 'ccps-portal-frontend'
              publishLocation: 'Container'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Docker Artifacts - Backend'
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/backend'
              ArtifactName: 'ccps-portal-backend'
              publishLocation: 'Container'
